formatter: markdown table

version: ">= 0.20"

recursive:
  enabled: false

sections:
  show:
    - resources
    - requirements
    - inputs
    - outputs

content: |-
  ## Table of Contents

  - [Overview](#overview)
  - [Key Features](#key-features)
  - [Usage](#usage)
  - [Requirements](#requirements)
  - [Inputs](#inputs)
  - [Outputs](#outputs)

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject

# sort variables by required, then name
sort:
  enabled: true
  by: required
